# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('itemID', models.IntegerField()),
                ('tableloc', models.CharField(max_length=1)),
                ('spec', models.CharField(max_length=255)),
                ('category', models.IntegerField()),
            ],
        ),
    ]
